<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Product>Git Tab Sync</Product>
    <Company>Eterletzki</Company>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>

</Project>
